version: '3.8'

services:
  server:
    build: ./server
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app

  front:
    build: ./Front/vite-project
    ports:
      - "5173:80"
    depends_on:
      - server
