version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./server:/app
    restart: always
    networks:
      - app
    container_name: musicbox-server

  front:
    build:
      context: ./Front/vite-project
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - server
    volumes:
      - ./Front/vite-project:/app
    restart: always
    networks:
      - app
    container_name: musicbox

networks:
  app:
    driver: bridge
